baseURL: https://cat2koban.dev/
languageCode: en-us
title: cat2koban.dev
theme: hugo-tania

params:
  twitterName: cat2koban

menu:
  header:
    - name: About
      url: "/about/"
    - name: Tags
      url: "/tags/"
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
