template: static/tcard/template_simple.png
title:
  start:
    px: 145
    py: 180
  fgHexColor: "#000000"
  fontSize: 64
  fontStyle: Bold
  maxWidth: 928
  lineSpacing: 10
category:
  start:
    px: 0
    py: 0
  fgHexColor: "#FFFFFF"
  fontSize: 1
  fontStyle: Regular
info:
  start:
    px: 250
    py: 470
  fgHexColor: "#A0A0A0"
  fontSize: 38
  fontStyle: Regular
  separator: " - "
tags:
  start:
    px: 840
    py: 473
  fgHexColor: "#FFFFFF"
  bgHexColor: "#6ab0f3"
  fontSize: 22
  fontStyle: Medium
  boxAlign: Left
  boxSpacing: 6
  boxPadding:
    top: 6
    right: 10
    bottom: 6
    left: 8
